### PR TITLE
Removed dependency on com.unity.textmeshpro.

### PR DESCRIPTION
**Pull request by vertxxyz**
As of 2023.2.0a14 `com.unity.textmeshpro` has been merged into uGUI `com.unity.ugui`, this requires TMP become an optional dependency.
- Defined out classes and references to TMP.
- Created fallback editors for classes users may expect to exist.
- Updated changelog.

* **Please check if the pull request fulfills these requirements**
- [N/A] Tests for the changes have been added (for bug fixes / features)
  - [N/A] Does it pass all existing unit tests without modification?
    - If not, what did you change?
    - If you altered it significantly, what coverage issue did you fix?
- [N/A] Docs have been added / updated (for bug fixes / features)
- [x] CHANGELOG.md has been updated to describe this change

* **What kind of change does this pull request introduce?**
- [x] Bug Fix
- [x] Feature
- [ ] Something else

* **What is the current behavior?**
YarnSpinner will not compile on 2023.2.0a14+ due to the deprecated TMP package.

* **What is the new behavior (if this is a feature change)?**
YarnSpinner supports 2023.2.0a14+, and now TMP is an optional dependency.  
When TMP (or UGUI 2.0.0+) are not installed then a helpbox is shown on the incompatible example dialogue view components:
image
Otherwise they function normally.

* **Does this pull request introduce a breaking change?**
If users do not have TMP referenced into their project (should be a default these days) then it will cause the incompatible dialogue view components to become disabled, and the serialized data could be lost if they ignore the change.
Contributors will have to use `USE_TMP`, and treat TextMeshPro as an optional dependency.

* **Other information**:
I can't think of a more appropriate way to make this change, but this cannot be a part of a minor release due to the potential breaking changes.

I tested these configurations after my changes:
- 2023.2.0a14+ now with UGUI 2.0.0+
- 2023.2.0a13 with TMP
- 2023.2.0a13 without TMP and UGUI <2.0.0
All compile and incompatible types display the new fallback editor.

### CODE REVIEW

**Comment by McJones** [comment]
Hey thanks for the PR this looks great and really comprehensive.
We haven't merged it yet because honestly we don't really like that Unity has put us in this situation and we've been trying to figure out if there is a better solution and are still coming up blank.
I imagine this will get accepted and merged if we can't come up with a different solution.

**Comment by mobychan** [comment]
@McJones Any news on this?
I want to play with some features in the newer Unity Versions but am blocked by this right now. Though I can totally understand being annoyed by this change...

**Comment by vertxxyz** [comment]
Looking at this again I'm not *completely* happy with the warning text I chose on the editors, so I might update those to be specific about which package needs to be installed based on the current version, and be less specific about the version (using greater than).

I couldn't think of a better way to do this, and having TMP be optional is ultimately a good idea for those who have transitioned to UI Toolkit. Though I think dependencies on Unity UI are pretty unavoidable, it's reasonable to expect this to lessen as UI Toolkit matures.

**Comment by spirifoxy** [comment]
Hi @McJones , any news on this?

**Comment by McJones** [comment]
We spent a little bit of time thinking about this issue and PR today and we are gonna take a slight tweak of this PR.
The core of this PR is to remove TMP from the dependency and then check for its absence via a defined `USE_TMP` flag.
We like the core idea and approach, we want to simplify the modifications to the built in dialogue views though.

Where what we are thinking differs is we will create a new TMP shim class that will mimic the necessary interface of TMP so the built in classes won’t have to have any changes other than the using import.
I will start working on modifying the PR to make this happen soon.

If you **absolutely** need this for now in the 2023 beta I would suggest modifying the package.json to remove the TMP dependency as the built in UGUI in the beta will just work.
